// Computed integer signal scopes: native samples, BT.709, area, matte and comparison data.
const assert = require('node:assert/strict');

(async () => {
  const { signalLevels, computeSignalHistogram } = await import('../src/core/signal-scopes.mjs');
  const { computeWaveform } = await import('../src/core/waveform.mjs');
  const { analysisDelta } = await import('../src/core/analysis-delta.mjs');
  const { analysisMaximum, analysisJSON } = await import('../src/core/analysis-output.mjs');
  const image = pixels => ({ width: pixels.length, height: 1, data: Uint8ClampedArray.from(pixels.flat()) });
  const black = image([[0, 0, 0, 255]]), white = image([[255, 255, 255, 255]]);
  const red = image([[255, 0, 0, 255]]), transparent = image([[255, 0, 0, 0]]);
  assert.deepEqual(signalLevels(0, 0, 0), [0, 128, 128]);
  assert.deepEqual(signalLevels(255, 255, 255), [255, 128, 128]);
  assert.equal(signalLevels(255, 0, 0)[0], 54);
  assert.equal(signalLevels(255, 0, 0)[2], 255);
  assert.equal(signalLevels(0, 0, 255)[1], 255);
  for (const [source, matte, expected] of [[transparent, 'white', 255], [transparent, 'black', 0]]) {
    const hist = computeSignalHistogram(source, matte), wave = computeWaveform(source, matte);
    assert.equal(hist.channels[0][expected], 1);
    assert.equal(hist.channels[1][128], 1);
    assert.equal(hist.channels[2][128], 1);
    assert.equal(wave.channels[3][expected], 1);
    assert.equal(wave.channels[4][128], 1);
    assert.equal(wave.channels[5][128], 1);
  }
  const mixed = image([[0,0,0,255],[255,0,0,255],[255,255,255,255]]);
  const area = { unit:'pixels', x: 1, y: 0, width: 1, height: 1 };
  const histogram = computeSignalHistogram(mixed, 'white', area);
  assert.equal(histogram.pixelCount, 1);
  assert.equal(histogram.channels[0][54], 1);
  assert.equal(histogram.channels[2][255], 1);
  assert.deepEqual(histogram.channels.map(c => c.reduce((a,b) => a+b,0)), [1,1,1]);
  const wave = computeWaveform(mixed, 'white', area);
  for (const [i,v] of signalLevels(255,0,0).entries()) assert.equal(wave.channels[i+3][v], 1);
  assert.equal(wave.columns, 1);
  assert.equal(analysisMaximum('signalHistogram', [{data: histogram}]), 100);
  assert.equal(analysisMaximum('ycbcrParade', [{data: wave}]), 1);
  assert.equal(analysisMaximum('rgbWaveform', [{data: wave}]), 1);
  const pair = (a,b) => [{cell:1,data:a},{cell:2,data:b}];
  const histDelta = analysisDelta(pair(computeSignalHistogram(black), computeSignalHistogram(white)), {type:'signalHistogram',channel:'rgb'});
  assert.equal(histDelta.maximum, 100);
  assert.equal(histDelta.channels.length, 3);
  assert.equal(histDelta.channels[0].values[0], -100);
  assert.equal(histDelta.channels[0].values[255], 100);
  for (const type of ['rgbWaveform','ycbcrParade']) {
    const delta = analysisDelta(pair(computeWaveform(black),computeWaveform(red)), {type});
    assert.equal(delta.channels.length, 3);
    assert.equal(delta.unit,'percentage-points');
    assert.equal(delta.alignment,'relative-column-area');
    assert.ok(JSON.parse(analysisJSON({delta})).delta.channels[0].values.length === 256);
  }
  const pixels16 = samples => ({ width:samples.length, height:1, data:Uint16Array.from(samples.flat()), sampleType:'uint16', bitDepth:16, colorSpace:'srgb', alphaMode:'straight' });
  const native = pixels16([[32769,32768,32767,65535],[0,65535,0,32768],[65535,0,0,0]]);
  const nativeCopy = native.data.slice();
  const signal16=computeSignalHistogram(native,'black',{unit:'pixels',x:0,y:0,width:2,height:1});
  assert.equal(signal16.sampleType,'uint16');assert.equal(signal16.scale.max,65535);
  assert.equal(signal16.channels[0].reduce((sum,count)=>sum+count,0),2);
  assert.equal(signal16.channels[0][Math.round((2126*32769+7152*32768+722*32767)/10000)],1);
  assert.equal(signal16.means[0],(signal16.channelMin[0]+signal16.channelMax[0])/2);
  const transparent16=computeSignalHistogram(pixels16([[12345,20000,30000,0]]),'white');
  assert.equal(transparent16.channels[0][65535],1);
  assert.equal(transparent16.channels[1][32768],1);
  assert.equal(transparent16.channels[2][32768],1);
  const precise = computeWaveform(native,'black',{unit:'pixels',x:0,y:0,width:2,height:1});
  assert.equal(precise.sampleType,'uint16');assert.equal(precise.bitDepth,16);
  assert.equal(precise.scaleMax,65535);assert.equal(precise.levelBins,1024);
  assert.equal(precise.columns,2);assert.equal(precise.pixelCount,2);
  assert.equal(precise.channels[0][512],1,'RGB is grouped after reading the exact 16-bit value');
  assert.equal(precise.channelMin[0],0);assert.equal(precise.channelMax[0],32769);
  assert.equal(precise.means[0],(32769+0)/2,'summary retains the native 16-bit value');
  assert.equal(precise.channels[3].reduce((sum,count)=>sum+count,0),2);
  assert.equal(precise.channels[4].reduce((sum,count)=>sum+count,0),2);
  assert.deepEqual(native.data,nativeCopy,'the source PixelBuffer is borrowed, not modified');
  const white16 = computeWaveform(pixels16([[12345,20000,30000,0]]),'white');
  assert.deepEqual(white16.channelMin.slice(0,3),[65535,65535,65535]);
  assert.deepEqual(white16.channelMin.slice(3),[65535,32768,32768]);
  assert.equal(analysisMaximum('rgbWaveform',[{data:precise}]),1);
  const matching8=computeWaveform(image([[255,0,0,255]]));
  const matching16=computeWaveform(pixels16([[65535,0,0,65535]]));
  const mixedDelta=analysisDelta(pair(matching8,matching16),{type:'parade'});
  assert.equal(mixedDelta.maximum,0,'8/16-bit matching endpoints align on the common grid');
  assert.equal(mixedDelta.rows,256);
  assert.equal(analysisMaximum('parade',[{data:matching8},{data:matching16}],'rgb',256),1);
  assert.equal(JSON.parse(analysisJSON({wave:matching16})).wave.channels[0].length,1024);
  const signalMixed=analysisDelta(pair(computeSignalHistogram(black),computeSignalHistogram(pixels16([[0,0,0,65535]]))),{type:'signalHistogram',channel:'rgb'});
  assert.equal(signalMixed.maximum,0,'matching 8/16 signal levels align after grouping');
  assert.equal(signalMixed.scale.normalized,true);
  assert.equal(signalMixed.alignment,'normalized-256-groups');
  assert.equal(JSON.parse(analysisJSON({signal:signal16})).signal.channels[0].length,65536);
  assert.throws(()=>computeWaveform({width:1,height:1,data:new Float32Array([0,0,0,1]),sampleType:'float32'}),/float32/);
  assert.throws(()=>computeWaveform(pixels16([[0,0,0,65535]]),'invalid'),/подложка/);
  assert.throws(() => computeSignalHistogram(red,'invalid'));
  assert.throws(()=>computeSignalHistogram({width:1,height:1,data:new Float32Array([0,0,0,1]),sampleType:'float32'}),/float32/);
  console.log('PASS BT.709 native RGBA8/16 signal levels, matte, ROI, bounded bins, mixed-depth comparison and JSON');
})().catch(error => { console.error(error); process.exitCode = 1; });
