const assert=require('node:assert/strict');
const pako=require('../vendor/pako-2.1.0.min.js');

(async()=>{
  const {createTiffFloatSample}=await import('../src/core/reference-samples.mjs');
  const {decodeTiffFloat}=await import('../src/core/tiff-float.mjs');
  const {computeHistogram}=await import('../src/core/histogram.mjs');
  const sample=createTiffFloatSample(),original=sample.bytes;
  assert.deepEqual(createTiffFloatSample().bytes,original);
  const decoded=decodeTiffFloat(original.buffer,0,pako);
  assert.equal(decoded.pixels.sampleType,'float32');
  assert.equal(decoded.pixels.colorSpace,'unknown');
  assert.equal(decoded.pages,1);
  assert.deepEqual(decoded.pixels.data,sample.pixels.data);
  assert.ok(decoded.stats.min[0]<0&&decoded.stats.max[0]>1);
  assert.equal(decoded.stats.visibleMin[0],decoded.pixels.data[16*4],
    'Auto display ignores hidden RGB samples while exact source statistics retain them');
  assert.equal(decoded.stats.visibleMax[0],decoded.stats.max[0]);
  assert.ok(decoded.stats.negative>0&&decoded.stats.aboveOne>0);
  assert.equal(decoded.pixels.data[3],0);
  assert.equal(decoded.preview[0],0);
  const middle=(16*64+32)*4;
  assert.equal(decoded.pixels.data[middle+3],1);
  const histogram=computeHistogram(decoded.pixels,'white',null,{range:[-0.5,2],bins:256,floatPeak:1});
  assert.equal(histogram.pixelCount,64*32);
  assert.equal(histogram.scale.kind,'float');
  assert.equal(histogram.channels[3].reduce((a,b)=>a+b,0),64*32);
  const view=new DataView(original.buffer);
  const entry=tag=>{for(let i=0;i<view.getUint16(8,true);i++){const at=10+i*12;if(view.getUint16(at,true)===tag)return at;}throw Error('missing '+tag);};
  const edit=(change)=>{const copy=original.slice(),v=new DataView(copy.buffer);change(v,copy);return copy.buffer;};
  assert.throws(()=>decodeTiffFloat(edit(v=>v.setUint16(entry(338)+8,1,true)),0,pako),/независимой alpha/);
  assert.throws(()=>decodeTiffFloat(edit(v=>v.setUint32(entry(273)+8,original.length-2,true)),0,pako),/полоса/);
  assert.throws(()=>decodeTiffFloat(edit(v=>v.setFloat32(view.getUint32(entry(273)+8,true),NaN,true)),0,pako),/неконечный/);
  assert.throws(()=>decodeTiffFloat(edit(v=>v.setFloat32(view.getUint32(entry(273)+8,true)+12,2,true)),0,pako),/alpha вне/);
  assert.throws(()=>decodeTiffFloat(edit(v=>{v.setUint16(entry(256)+8,65535,true);v.setUint16(entry(257)+8,65535,true);}),0,pako),/8 мегапикселей/);
  assert.throws(()=>decodeTiffFloat(edit(v=>v.setUint16(entry(259)+8,5,true)),0,pako),/Deflate/);
  const pixelAt=view.getUint32(entry(273)+8,true),compressed=pako.deflate(original.subarray(pixelAt));
  const deflated=new Uint8Array(pixelAt+compressed.length);deflated.set(original.subarray(0,pixelAt));deflated.set(compressed,pixelAt);
  const deflateView=new DataView(deflated.buffer);
  deflateView.setUint16(entry(259)+8,8,true);deflateView.setUint32(entry(279)+8,compressed.length,true);
  assert.deepEqual(decodeTiffFloat(deflated.buffer,0,pako).pixels.data,sample.pixels.data);
  const broken=deflated.slice();broken[broken.length-1]^=0xff;
  assert.throws(()=>decodeTiffFloat(broken.buffer,0,pako),/Deflate|полоса/);
  console.log('PASS exact TIFF float32, SDR clipping, range analysis, Deflate and explicit rejection');
})().catch(error=>{console.error(error);process.exitCode=1;});
