const assert=require('node:assert/strict');

(async()=>{
  const {wipePair,visibleGridLines,visibleJpegBlockLines,visibleCodecBlockLines,visibleCodecBlockCells,jpegBlockSize,codecGridSpec}=await import('../src/core/wipe-view.mjs');
  const first={bitmap:{width:960,height:640}},second={bitmap:{width:960,height:640}};
  assert.deepEqual(wipePair(first,second,()=>true),{width:960,height:640});
  assert.match(wipePair(first,second,variant=>variant!==second).message,/готовности/);
  assert.match(wipePair(first,{bitmap:{width:480,height:320}},()=>true).message,/одинаковые размеры/);
  assert.deepEqual(visibleGridLines(-16,16,100,80,16),{first:1,last:6});
  assert.equal(visibleGridLines(-16,16,100,80,7),null,'grid remains hidden below eight CSS pixels');
  assert.equal(visibleGridLines(0,8,1000,4000,8),null,'line budget prevents excessive drawing');
  assert.equal(visibleGridLines(-1000,8,10,100,8),null,'off-screen image has no grid lines');
  assert.deepEqual(jpegBlockSize('444'),{width:8,height:8});
  assert.deepEqual(jpegBlockSize('422'),{width:16,height:8});
  assert.deepEqual(jpegBlockSize('420'),{width:16,height:16});
  assert.equal(visibleJpegBlockLines(0,2.9,960,600,2.9),null,'block lines remain hidden until readable');
  assert.deepEqual(visibleJpegBlockLines(-16,3,100,100,3),{first:1,last:4},'block lines stay anchored to image coordinates after panning');
  assert.equal(visibleJpegBlockLines(0,3,4000,12000,3),null,'very dense block views have a line budget');
  assert.deepEqual(visibleCodecBlockLines(-32,1.5,200,180,1.5,16),{first:2,last:8});
  assert.equal(visibleCodecBlockLines(0,1,200,180,1,16),null,'WebP blocks remain hidden until readable');
  assert.deepEqual(visibleCodecBlockCells(-896,64,32,256,64,8),{first:1,last:2},'visible VarDCT columns include the cell before a crossing');
  assert.deepEqual(visibleCodecBlockCells(-128,64,32,256,64,8),{first:0,last:0},'visible VarDCT rows remain available without a horizontal crossing');
  assert.equal(visibleCodecBlockCells(-3000,64,32,256,64,8),null,'fully off-screen blocks do not draw');
  assert.deepEqual(codecGridSpec({format:'jpeg',jpegSubsampling:'420'}),{kind:'jpeg',step:8,width:16,height:16});
  assert.deepEqual(codecGridSpec({format:'webp'},{kind:'webp-vp8'}),{kind:'webp',step:16,width:16,height:16});
  assert.equal(codecGridSpec({format:'webp'},null),null);
  assert.equal(codecGridSpec({format:'avif'}),null);
  assert.equal(codecGridSpec({format:'heic'}),null);
  assert.deepEqual(codecGridSpec({format:'avif'},{kind:'avif-superblock',width:128,height:128}),{kind:'avif',step:128,width:128,height:128});
  assert.deepEqual(codecGridSpec({format:'heic'},{kind:'heic-ctu',width:32,height:32}),{kind:'heic',step:32,width:32,height:32});
  assert.equal(codecGridSpec({format:'jxl'}),null,'JPEG XL has no guessed 8×8 grid');
  const owners=new Uint32Array([1,1,3,4,1,1,7,8,9,10,11,12,13,14,15,16]);
  const jxlGrid={kind:'jxl-vardct',columns:4,rows:4,owners};
  assert.deepEqual(codecGridSpec({format:'jxl'},jxlGrid),{kind:'jxl',step:8,columns:4,rows:4,owners});
  assert.deepEqual(codecGridSpec({format:'jxlLossless'},jxlGrid),{kind:'jxl',step:8,columns:4,rows:4,owners});
  for(const format of ['original','png','webpLossless','jxlLossless','tiff'])assert.equal(codecGridSpec({format}),null);
  const {webpBlockGrid}=await import('../src/core/webp-blocks.mjs');
  const chunk=(name,payload)=>{
    const bytes=new Uint8Array(8+payload.length+(payload.length&1));
    for(let i=0;i<4;i++)bytes[i]=name.charCodeAt(i);
    new DataView(bytes.buffer).setUint32(4,payload.length,true);
    bytes.set(payload,8);return bytes;
  };
  const riff=(...chunks)=>{
    const length=12+chunks.reduce((total,part)=>total+part.length,0);
    const bytes=new Uint8Array(length);
    bytes.set([82,73,70,70],0);new DataView(bytes.buffer).setUint32(4,length-8,true);
    bytes.set([87,69,66,80],8);
    let offset=12;for(const part of chunks){bytes.set(part,offset);offset+=part.length;}
    return new Blob([bytes],{type:'image/webp'});
  };
  assert.deepEqual(await webpBlockGrid(riff(chunk('VP8 ',new Uint8Array(3)))),{kind:'webp-vp8',width:16,height:16});
  assert.deepEqual(await webpBlockGrid(riff(chunk('VP8X',new Uint8Array(10)),chunk('ALPH',new Uint8Array(5)),chunk('VP8 ',new Uint8Array(3)))),{kind:'webp-vp8',width:16,height:16});
  assert.equal(await webpBlockGrid(riff(chunk('VP8L',new Uint8Array(3)))),null,'lossless WebP is not a VP8 macroblock image');
  assert.equal(await webpBlockGrid(riff(chunk('ANIM',new Uint8Array(6)),chunk('VP8 ',new Uint8Array(3)))),null,'animation is not one still grid');
  const malformed=new Uint8Array(await riff(chunk('VP8 ',new Uint8Array(3))).arrayBuffer());
  new DataView(malformed.buffer).setUint32(16,999999,true);
  assert.equal(await webpBlockGrid(new Blob([malformed])),null,'out-of-bounds RIFF chunk is rejected');
  const {createCanvas}=await import('../src/ui/canvas.mjs');
  const strokes=[],segments=[];
  const context={save(){},restore(){},beginPath(){segments.length=0;},rect(){},clip(){},drawImage(){},
    setLineDash(value){this.dash=[...value];},
    moveTo(x,y){segments.push(['move',x,y]);},lineTo(x,y){segments.push(['line',x,y]);},
    stroke(){strokes.push({width:this.lineWidth,dash:this.dash||[],segments:segments.map(part=>[...part])});}};
  const preview={width:256,height:256,getBoundingClientRect:()=>({width:256,height:256})};
  const result={index:1,canvas:preview,ctx:context,bitmap:{width:32,height:32},resultConfig:{format:'jpeg',jpegSubsampling:'422'}};
  const gridApp={source:{width:32,height:32},view:{centerX:16,centerY:16},gridMode:'codec-blocks',pixelGrid:true};
  const drawing=createCanvas({app:gridApp,els:{}},{drawBackground(){},drawImageFrame(){},getDrawScale:()=>4,isVariantReady:()=>true});
  drawing.drawVariant(result);
  assert.equal(strokes.length,2,'JPEG grid has fine DCT lines and stronger MCU lines');
  assert.ok(strokes[0].segments.some(part=>part[0]==='move'&&part[1]===96.5),'first 8-pixel line uses the output origin');
  assert.ok(strokes[1].segments.some(part=>part[0]==='move'&&part[1]===128.5),'4:2:2 MCU has a 16-pixel horizontal period');
  assert.ok(strokes[1].segments.some(part=>part[0]==='move'&&part[2]===96.5),'4:2:2 MCU has an 8-pixel vertical period');
  strokes.length=0;result.resultConfig={format:'png'};drawing.drawVariant(result);
  assert.equal(strokes.length,0,'other formats do not receive an unsupported grid');
  result.resultConfig={format:'webp'};result.blockGrid={kind:'webp-vp8',width:16,height:16};
  drawing.drawVariant(result);
  assert.equal(strokes.length,1,'VP8 WebP has only its 16-pixel macroblock grid');
  assert.ok(strokes[0].segments.some(part=>part[0]==='move'&&part[1]===128.5));
  strokes.length=0;result.blockGrid=null;drawing.drawVariant(result);
  assert.equal(strokes.length,0,'unverified WebP has no inferred macroblock grid');
  result.resultConfig={format:'heic'};result.blockGrid={kind:'heic-ctu',width:16,height:16};
  drawing.drawVariant(result);
  assert.equal(strokes.length,1,'verified HEIC CTU uses a solid grid');
  assert.deepEqual(strokes[0].dash,[]);
  strokes.length=0;result.blockGrid=null;drawing.drawVariant(result);
  assert.equal(strokes.length,0,'unverified HEIC has no guessed CTU grid');
  result.resultConfig={format:'jxl'};result.blockGrid=jxlGrid;drawing.drawVariant(result);
  assert.equal(strokes.length,1,'verified JPEG XL draws exact strategy boundaries');
  assert.deepEqual(strokes[0].dash,[]);
  assert.ok(strokes[0].segments.some(part=>part[0]==='move'&&part[1]===128.5),'boundary follows the decoded 16-pixel-wide strategy');
  assert.ok(!strokes[0].segments.some(part=>part[0]==='move'&&part[1]===96.5&&part[2]===64),'no line inside a multiblock strategy');
  gridApp.view.centerX=16;gridApp.view.centerY=4;
  const zoomed=createCanvas({app:gridApp,els:{}},{drawBackground(){},drawImageFrame(){},getDrawScale:()=>64,isVariantReady:()=>true});
  strokes.length=0;zoomed.drawVariant(result);
  assert.ok(strokes[0].segments.some(part=>part[0]==='move'&&part[1]===128.5),'vertical VarDCT boundary survives with no horizontal grid crossing');
  gridApp.view.centerX=20;gridApp.view.centerY=8;
  strokes.length=0;zoomed.drawVariant(result);
  assert.ok(strokes[0].segments.some(part=>part[0]==='move'&&part[2]===128.5),'horizontal VarDCT boundary survives with no vertical grid crossing');
  result.resultConfig={format:'jpeg',jpegSubsampling:'420'};
  gridApp.view.centerX=16;gridApp.view.centerY=4;
  strokes.length=0;zoomed.drawVariant(result);
  assert.ok(strokes.some(stroke=>stroke.segments.some(part=>part[0]==='move'&&part[1]===128.5)),'regular codec boundary survives with only a vertical crossing');
  gridApp.view.centerX=4;gridApp.view.centerY=16;
  strokes.length=0;zoomed.drawVariant(result);
  assert.ok(strokes.some(stroke=>stroke.segments.some(part=>part[0]==='move'&&part[2]===128.5)),'regular codec boundary survives with only a horizontal crossing');
  gridApp.gridMode='pixels';
  strokes.length=0;zoomed.drawVariant(result);
  assert.ok(strokes.length,'pixel grid remains drawable without accessing codec-specific data');
  gridApp.gridMode='codec-blocks';gridApp.view.centerX=16;gridApp.view.centerY=16;
  result.resultConfig={format:'jxl'};
  strokes.length=0;result.blockGrid=null;drawing.drawVariant(result);
  assert.equal(strokes.length,0,'Modular or unverified JPEG XL has no grid');
  strokes.length=0;
  result.resultConfig={format:'jpeg',jpegSubsampling:'420'};
  const notReady=createCanvas({app:gridApp,els:{}},{drawBackground(){},drawImageFrame(){},getDrawScale:()=>4,isVariantReady:()=>false});
  notReady.drawVariant(result);
  assert.equal(strokes.length,0,'stale JPEG output does not receive a grid');
  const handle={style:{},attrs:{},setAttribute(key,value){this.attrs[key]=String(value);}};
  const modeApp={wipe:{active:false,position:.5,previousLayout:null},layout:4,source:null};
  const layouts=[];
  const canvas=createCanvas({app:modeApp,els:{wipeOverlay:{},wipeHandle:handle}},
    {clamp:(value,min,max)=>Math.max(min,Math.min(max,value)),updateLayout:count=>layouts.push(count)});
  canvas.setWipeMode(true);
  assert.equal(modeApp.wipe.active,true,'combined view can be selected before a file is opened');
  assert.deepEqual(layouts,[2]);
  canvas.setWipePosition(.37123);
  assert.equal(handle.style.left,'37.123%','visual boundary must keep the fractional position');
  assert.equal(handle.attrs['aria-valuenow'],'37','screen-reader value can remain rounded');
  const {createComparison}=await import('../src/ui/comparison.mjs');
  const variants=[0,1,2].map(index=>({index,ready:index<2,processing:false,
    cell:{classList:{contains:()=>index===2}}}));
  const app={variants,sourceGeneration:1},encoded=[];
  const comparison=createComparison({app,els:{}},{isVariantReady:variant=>variant.ready,
    renderVariant:async variant=>{encoded.push(variant.index);variant.ready=true;}});
  await comparison.renderVisibleVariants();
  assert.deepEqual(encoded,[],'switching to an aligned view must reuse ready outputs');
  variants[1].ready=false;
  await comparison.renderVisibleVariants();
  assert.deepEqual(encoded,[1],'only an invalidated visible output is encoded');
  console.log('PASS wipe pair readiness, exact verified codec grids and bounded JPEG XL drawing');
})().catch(error=>{console.error(error);process.exitCode=1;});
