import { DEFAULT_EXPORT_CONFIG } from './core/config.mjs';
import { DEFAULT_DISPLAY } from './core/display-sdr.mjs';

export function createState() {
  return {
  files: [],
  nextFileId: 1,
  selectedFileId: null,
  selectionGeneration: 0,
  listGeneration: 0,
  fileRows: new Map(),
  exportConfig: { ...DEFAULT_EXPORT_CONFIG },
  storageNotice: "",
  storageWarning: false,
  batchRun: null,
  batchPreview: { generation: 0, requestKey: null, pending: false, busy: false, timer: null,
    bitmap: null, blob: null, source: null, resultConfig: null, width: 0, height: 0,
    zoom: 1, centerX: 0.5, centerY: 0.5, pointer: null },
  samplePending: false,
  source: null,
  sourceError: "",
  sourceGeneration: 0,
  sourceLoading: false,
  layout: 2,
  wipe: { active: false, position: 0.5, previousLayout: null },
  pixelGrid: false,
  gridMode: 'pixels',
  display: { ...DEFAULT_DISPLAY },
  background: "checker",
  variants: [],
  support: new Map(),
  view: {
    centerX: 0,
    centerY: 0,
    zoom: 1
  },
  pointer: {
    active: false,
    id: null,
    lastX: 0,
    lastY: 0
  },
  statusTimer: null,
  codecs: {},
  codecPromises: {},
  codecAttempts: {},
  scriptPromises: new Map()
};
}

export function collectElements() {
  return {
  fileInput: document.getElementById("fileInput"),
  workspace: document.getElementById("workspace"),
  filePanel: document.getElementById("filePanel"),
  fileDropHint: document.getElementById("fileDropHint"),
  viewDropHint: document.getElementById("viewDropHint"),
  fileList: document.getElementById("fileList"),
  fileListEmpty: document.getElementById("fileListEmpty"),
  fileCount: document.getElementById("fileCount"),
  fileCountToggle: document.getElementById("fileCountToggle"),
  toggleFiles: document.getElementById("toggleFiles"),
  previousFile: document.getElementById("previousFile"),
  nextFile: document.getElementById("nextFile"),
  clearFiles: document.getElementById("clearFiles"),
  batchDialog: document.getElementById("batchDialog"),
  batchForm: document.getElementById("batchForm"),
  batchDialogCount: document.getElementById("batchDialogCount"),
  batchFormat: document.getElementById("batchFormat"),
  batchQualityField: document.getElementById("batchQualityField"),
  batchQuality: document.getElementById("batchQuality"),
  batchQualityNumber: document.getElementById("batchQualityNumber"),
  batchGifField: document.getElementById("batchGifField"),
  batchGifColors: document.getElementById("batchGifColors"),
  batchDitherField: document.getElementById("batchDitherField"),
  batchGifDither: document.getElementById("batchGifDither"),
  batchResizeMode: document.getElementById("batchResizeMode"),
  batchDimensions: document.getElementById("batchDimensions"),
  batchDialogWidth: document.getElementById("batchDialogWidth"),
  batchDialogHeight: document.getElementById("batchDialogHeight"),
  batchMatteField: document.getElementById("batchMatteField"),
  batchMatte: document.getElementById("batchMatte"),
  batchMetadata: document.getElementById("batchMetadata"),
  batchMetadataHint: document.getElementById("batchMetadataHint"),
  batchDialogSummary: document.getElementById("batchDialogSummary"),
  batchNameExample: document.getElementById("batchNameExample"),
  batchStorageNotice: document.getElementById("batchStorageNotice"),
  batchStorageWarning: document.getElementById("batchStorageWarning"),
  batchDialogError: document.getElementById("batchDialogError"),
  batchSaveSettings: document.getElementById("batchSaveSettings"),
  batchStart: document.getElementById("batchStart"),
  batchPreviewSource: document.getElementById("batchPreviewSource"),
  batchPreviewStatus: document.getElementById("batchPreviewStatus"),
  batchPreviewBefore: document.getElementById("batchPreviewBefore"),
  batchPreviewAfter: document.getElementById("batchPreviewAfter"),
  batchPreviewBeforeInfo: document.getElementById("batchPreviewBeforeInfo"),
  batchPreviewAfterInfo: document.getElementById("batchPreviewAfterInfo"),
  batchPreviewMetrics: document.getElementById("batchPreviewMetrics"),
  batchPreviewDownload: document.getElementById("batchPreviewDownload"),
  convertAll: document.getElementById("convertAll"),
  batchPanel: document.getElementById("batchPanel"),
  batchSummary: document.getElementById("batchSummary"),
  batchProgress: document.getElementById("batchProgress"),
  batchRunConfig: document.getElementById("batchRunConfig"),
  cancelBatch: document.getElementById("cancelBatch"),
  batchReport: document.getElementById("batchReport"),
  batchResults: document.getElementById("batchResults"),
  sampleImage: document.getElementById("sampleImage"),
  sampleMenuToggle: document.getElementById("sampleMenuToggle"),
  sampleMenu: document.getElementById("sampleMenu"),
  retryCodecs: document.getElementById("retryCodecs"),
  codecStatus: document.getElementById("codecStatus"),
  codecNotice: document.getElementById("codecNotice"),
  metadataPolicy: document.getElementById("metadataPolicy"),
  grid: document.getElementById("grid"),
  emptyState: document.getElementById("emptyState"),
  emptyTitle: document.getElementById("emptyTitle"),
  emptyMessage: document.getElementById("emptyMessage"),
  layout2: document.getElementById("layout2"),
  layout4: document.getElementById("layout4"),
  wipeMode: document.getElementById("wipeMode"),
  pixelGrid: document.getElementById("pixelGrid"),
  gridModeToggle: document.getElementById("gridModeToggle"),
  gridModeMenu: document.getElementById("gridModeMenu"),
  gridModePixels: document.getElementById("gridModePixels"),
  gridModeCodec: document.getElementById("gridModeCodec"),
  displayMenuToggle: document.getElementById("displayMenuToggle"),
  displayMenu: document.getElementById("displayMenu"),
  displayMode: document.getElementById("displayMode"),
  displayBlack: document.getElementById("displayBlack"),
  displayWhite: document.getElementById("displayWhite"),
  displayExposure: document.getElementById("displayExposure"),
  displayDither: document.getElementById("displayDither"),
  displayBlackValue: document.getElementById("displayBlackValue"),
  displayWhiteValue: document.getElementById("displayWhiteValue"),
  displayExposureValue: document.getElementById("displayExposureValue"),
  displayOutputNote: document.getElementById("displayOutputNote"),
  wipeOverlay: document.getElementById("wipeOverlay"),
  wipeCanvas: document.getElementById("wipeCanvas"),
  wipeHandle: document.getElementById("wipeHandle"),
  backgroundSelect: document.getElementById("backgroundSelect"),
  resetView: document.getElementById("resetView"),
  fitView: document.getElementById("fitView"),
  status: document.getElementById("status")
};
}
